version: '3.8'

services:
  test:
    build: .
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongodb:27017/movie-director-test
      - REDIS_HOST=redis
      - NATS_URL=nats://nats:4222
    depends_on:
      - mongodb
      - redis
      - nats
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm test

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_test:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_test:/data

  nats:
    image: nats:latest
    ports:
      - "4223:4222"
      - "8223:8222"
    command: ["--http_port", "8222"]

volumes:
  mongodb_test:
  redis_test: 